// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortServiceClient interface {
	CreateOrUpdateStream(ctx context.Context, opts ...grpc.CallOption) (PortService_CreateOrUpdateStreamClient, error)
	List(ctx context.Context, in *ListQuery, opts ...grpc.CallOption) (*PortListData, error)
}

type portServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortServiceClient(cc grpc.ClientConnInterface) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) CreateOrUpdateStream(ctx context.Context, opts ...grpc.CallOption) (PortService_CreateOrUpdateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &PortService_ServiceDesc.Streams[0], "/port.PortService/CreateOrUpdateStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &portServiceCreateOrUpdateStreamClient{stream}
	return x, nil
}

type PortService_CreateOrUpdateStreamClient interface {
	Send(*Port) error
	CloseAndRecv() (*SendBatchResponse, error)
	grpc.ClientStream
}

type portServiceCreateOrUpdateStreamClient struct {
	grpc.ClientStream
}

func (x *portServiceCreateOrUpdateStreamClient) Send(m *Port) error {
	return x.ClientStream.SendMsg(m)
}

func (x *portServiceCreateOrUpdateStreamClient) CloseAndRecv() (*SendBatchResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendBatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portServiceClient) List(ctx context.Context, in *ListQuery, opts ...grpc.CallOption) (*PortListData, error) {
	out := new(PortListData)
	err := c.cc.Invoke(ctx, "/port.PortService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortServiceServer is the server API for PortService service.
// All implementations must embed UnimplementedPortServiceServer
// for forward compatibility
type PortServiceServer interface {
	CreateOrUpdateStream(PortService_CreateOrUpdateStreamServer) error
	List(context.Context, *ListQuery) (*PortListData, error)
	mustEmbedUnimplementedPortServiceServer()
}

// UnimplementedPortServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPortServiceServer struct {
}

func (UnimplementedPortServiceServer) CreateOrUpdateStream(PortService_CreateOrUpdateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateOrUpdateStream not implemented")
}
func (UnimplementedPortServiceServer) List(context.Context, *ListQuery) (*PortListData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPortServiceServer) mustEmbedUnimplementedPortServiceServer() {}

// UnsafePortServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortServiceServer will
// result in compilation errors.
type UnsafePortServiceServer interface {
	mustEmbedUnimplementedPortServiceServer()
}

func RegisterPortServiceServer(s grpc.ServiceRegistrar, srv PortServiceServer) {
	s.RegisterService(&PortService_ServiceDesc, srv)
}

func _PortService_CreateOrUpdateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PortServiceServer).CreateOrUpdateStream(&portServiceCreateOrUpdateStreamServer{stream})
}

type PortService_CreateOrUpdateStreamServer interface {
	SendAndClose(*SendBatchResponse) error
	Recv() (*Port, error)
	grpc.ServerStream
}

type portServiceCreateOrUpdateStreamServer struct {
	grpc.ServerStream
}

func (x *portServiceCreateOrUpdateStreamServer) SendAndClose(m *SendBatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *portServiceCreateOrUpdateStreamServer) Recv() (*Port, error) {
	m := new(Port)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PortService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/port.PortService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).List(ctx, req.(*ListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// PortService_ServiceDesc is the grpc.ServiceDesc for PortService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "port.PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _PortService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateOrUpdateStream",
			Handler:       _PortService_CreateOrUpdateStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "common/pb/port.proto",
}
